### ISSUE TITLE
Setup issue

### ISSUE THREAD

**Issue by agilewebsolutions** [vwt12eh8/hassio-ecoflow#101]
Logger: homeassistant.config_entries
Source: config_entries.py:2077
First occurred: 12:25:23 (1 occurrences)
Last logged: 12:25:23

Error occurred loading flow for integration ecoflow: cannot import name 'Observable' from 'reactivex' (/usr/local/lib/python3.11/site-packages/reactivex/__init__.py)

**Comment by agilewebsolutions** [comment]
Logger: homeassistant.config_entries
Source: config_entries.py:402
First occurred: 10:42:45 (1 occurrences)
Last logged: 10:42:45
Error setting up entry for ecoflow

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 402, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ecoflow/__init__.py", line 429, in async_setup_entry
    hass.config_entries.async_setup_platforms(entry, _PLATFORMS)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'

**Comment by lwsrbrts** [comment]
https://github.com/vwt12eh8/hassio-ecoflow/pull/79
