### ISSUE TITLE
Help with an error in homeassistant Connection reset by peer

### ISSUE THREAD

**Issue by Jordyleef** [vwt12eh8/hassio-ecoflow#43]
Traceback (most recent call last):
  File "/config/custom_components/ecoflow/ecoflow/rxtcp.py", line 71, in __loop
    data = await self.__rx.read(1024)
  File "/usr/local/lib/python3.10/asyncio/streams.py", line 669, in read
    await self._wait_for_data('read')
  File "/usr/local/lib/python3.10/asyncio/streams.py", line 502, in _wait_for_data
    await self._waiter
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 854, in _read_ready__data_received
    data = self._sock.recv(self.max_size)
ConnectionResetError: [Errno 104] Connection reset by peer

this is the error i get in homeassistant logs.

**Comment by Jordyleef** [comment]
> Traceback (most recent call last): File "/config/custom_components/ecoflow/ecoflow/rxtcp.py", line 71, in __loop data = await self.__rx.read(1024) File "/usr/local/lib/python3.10/asyncio/streams.py", line 669, in read await self._wait_for_data('read') File "/usr/local/lib/python3.10/asyncio/streams.py", line 502, in _wait_for_data await self._waiter File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 854, in _read_ready__data_received data = self._sock.recv(self.max_size) ConnectionResetError: [Errno 104] Connection reset by peer
> 
> this is the error i get in homeassistant logs.

I only get it from time to time. I found the disabling the ecoflow integrations and the enabling it works the restore normale funtion.
