### ISSUE TITLE
Ecoflow Entities not working since firmware 1.0.1.49

### ISSUE THREAD

**Issue by jptremblaygci** [vwt12eh8/hassio-ecoflow#85]
Hi all, 

Everything was looking great at the version 1.0.1.18 but since the latest firmware for the delta Pro, Nothing is working anymore. I deleted my entities in homeassistant and try to add it again but it look like the Ecoflow API has been changed on their side. The wizard do not even detect Ecoflow Pro IP, nothing happen

Am I the only one with this issue?

**Comment by dltccf** [comment]
Mine is working mostly fine on 1.0.1.49. I see only 63 entities which I believe are due to several variables being changed to add the energy management. When you upgraded, did it also upgrade the WIFI version? What version in your WIFI now? that is most likely the source of your problem.

**Comment by jptremblaygci** [comment]
My Wifi version is 3.0.1.11. Do you have the same?

**Comment by dltccf** [comment]
No, If you look at other comments about firmware here you will see that 3.0.1.11 blocks it from working. To fix it you will have to email ecoflow and ask to be upgraded from 3.0.1.11 to 3.0.2.21. I had to do this to get mine working. Took several days before the update went through. I even had to completely uninstall and reinstall the app on my phone to get the upgrade to complete, but finally it did.

**Comment by Alaskapclos** [comment]
I get crazy with ecoflow support...three different people told me, there is no other firmware 3.0.2.21 available....wtf...

**Comment by Mike-DUS** [comment]
I just got a few days back the Info that this is general available and could update.
Anyhow my DP is not recognised by the Integration.

![IMG_8738](https://github.com/vwt12eh8/hassio-ecoflow/assets/91613615/e513758d-7263-4163-8ef9-fb970501ff56)


I did a full removal and fresh installation (Incl. several reboots after every step) but no success until now.

I also have observed a new Firmware after reinstalling the app but cannot update it.

![IMG_8729](https://github.com/vwt12eh8/hassio-ecoflow/assets/91613615/f9705745-c165-4fce-9c7b-cc8b86473516)
![IMG_8730](https://github.com/vwt12eh8/hassio-ecoflow/assets/91613615/8d9b32e2-d966-40bf-ad14-598806b7bec1)

Any Idea on how to get it working ?

Home Assistant 2023.6.2
Supervisor 2023.06.2
Operating System 10.2
Frontend 20230608.0 - latest

Found this in the Log:

Logger: homeassistant.config_entries
Source: custom_components/ecoflow/__init__.py:275
Integration: Ecoflow (documentation, issues)
First occurred: 12:41:47 (1 occurrences)
Last logged: 12:41:47

Error setting up entry DELTA Pro 200245 for ecoflow
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ecoflow/__init__.py", line 275, in async_setup_entry
    hass.config_entries.async_setup_platforms(entry, _PLATFORMS)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'


Thx Mike

**Comment by dltccf** [comment]
Mike-DUS look at issue #76

**Comment by Mike-DUS** [comment]
> Mike-DUS look at issue #76

Thanks, now it is working.

**Comment by Nick75wien** [comment]
I also have problems with making it working-just yesterday got my delta Pro. Tried to figure it out here and did post 76 but still this is what happens: 
![IMG_2380](https://github.com/vwt12eh8/hassio-ecoflow/assets/103947456/e14503a2-48a0-4ddb-a385-8be76cbf2f3b)
![IMG_2381](https://github.com/vwt12eh8/hassio-ecoflow/assets/103947456/3f2ee9af-909f-4df0-9db0-28508a3ce310)

**Comment by iBobik** [comment]
How it looks with Delta Pro:
<details>

<summary>Screenshots</summary>

"Není k dispozici" means Not available.
![Snímek obrazovky 2023-10-14 v 13 38 47](https://github.com/vwt12eh8/hassio-ecoflow/assets/614232/3c43c98b-6027-4e41-b33d-ab81c3e2af3b)
![Snímek obrazovky 2023-10-14 v 13 39 17](https://github.com/vwt12eh8/hassio-ecoflow/assets/614232/1e1cb020-cecc-4971-9294-6e630cca4736)
![Snímek obrazovky 2023-10-14 v 13 39 28](https://github.com/vwt12eh8/hassio-ecoflow/assets/614232/dde6b6ce-24b3-4989-8e95-b9aec6130aa6)
![Snímek obrazovky 2023-10-14 v 13 39 39](https://github.com/vwt12eh8/hassio-ecoflow/assets/614232/f39e1f09-411d-417a-9d74-88118fb4b7be)
![Snímek obrazovky 2023-10-14 v 13 39 43](https://github.com/vwt12eh8/hassio-ecoflow/assets/614232/886895e1-f5af-4726-9d66-6e112d950032)
![Snímek obrazovky 2023-10-14 v 13 39 50](https://github.com/vwt12eh8/hassio-ecoflow/assets/614232/573ec357-1c7d-4daa-a107-086e7c3c2a0f)
</details>

Also there is this log message:
```
Logger: custom_components.ecoflow.ecoflow.rxtcp
Source: custom_components/ecoflow/ecoflow/rxtcp.py:71
Integration: Ecoflow (documentation, issues)
First occurred: 01:42:35 (401 occurrences)
Last logged: 13:32:14

[Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/config/custom_components/ecoflow/ecoflow/rxtcp.py", line 71, in __loop
    data = await self.__rx.read(1024)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/streams.py", line 694, in read
    await self._wait_for_data('read')
  File "/usr/local/lib/python3.11/asyncio/streams.py", line 526, in _wait_for_data
    await self._waiter
  File "/usr/local/lib/python3.11/asyncio/selector_events.py", line 989, in _read_ready__data_received
    data = self._sock.recv(self.max_size)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer
```
