### ISSUE TITLE
Does updating to 1.0.1.61 firmware break integration? (Delta Pro)

### ISSUE THREAD

**Issue by Maxctran** [vwt12eh8/hassio-ecoflow#97]
If you have followed my previous posts you will be aware that I have integrated my Smart Home Panel to automate charging with Glow CAD smart meter. Everything is working, I am running firmware 1.0.1.18 on each Delta Pro. The app keeps telling me there is a new official firmware 1.0.1.61 which it wants me to update the Delta Pros to. I am just wondering if anyone has updated it and if this has caused any problems with the integration not working anymore? 

I am currently too scared to update it in case it breaks everything but the changelog has definitely attractive fix of sorting out the excessive fan noise which would be useful but I am currently taking 'if its not broke don't try to fix it' mantra.

**Comment by Roughman007** [comment]
Hi, based on the communication with EcoFlow support, I updated the firmware to version 1.0.1.16 (wifi version 3.0.2.21 remained unchanged). HA integration still works.

**Comment by Maxctran** [comment]
Thats great news I may risk the update then, anyone else able to confirm it hasn't messed up their HA integration after the firmware was updated?

**Comment by kchiem** [comment]
I'm on V1.0.1.61 and V3.0.1.11 (Wi-Fi) and it's broken for me.  Logs show:

```
2023-10-18 16:29:55.335 DEBUG (MainThread) [custom_components.ecoflow.ecoflow.rxtcp] connecting 192.168.0.75
2023-10-18 16:29:55.339 DEBUG (MainThread) [custom_components.ecoflow.ecoflow.rxtcp] [Errno 111] Connect call failed ('192.168.0.75', 8055)
2023-10-18 16:29:55.582 DEBUG (MainThread) [custom_components.ecoflow.ecoflow.rxtcp] connecting 192.168.0.75
2023-10-18 16:29:55.584 DEBUG (MainThread) [custom_components.ecoflow.ecoflow.rxtcp] connecting 192.168.0.75
2023-10-18 16:29:55.587 DEBUG (MainThread) [custom_components.ecoflow.ecoflow.rxtcp] [Errno 111] Connect call failed ('192.168.0.75', 8055)
2023-10-18 16:29:55.589 DEBUG (MainThread) [custom_components.ecoflow.ecoflow.rxtcp] [Errno 111] Connect call failed ('192.168.0.75', 8055)
```
UPDATE: also found these:
```
Error setting up entry DELTA Pro 190### for ecoflow
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 399, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ecoflow/__init__.py", line 275, in async_setup_entry
    hass.config_entries.async_setup_platforms(entry, _PLATFORMS)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'
```

**Comment by michael5411** [comment]
My EcoFlow Delta Pro broke down after 3.570 hours and I got a replacement (to save time, not waiting for repair of my EF).

It is equipped with V1.0.1.61 and V3.0.1.11 (Wi-Fi) and it's broken for me, too. 
It`s a pity that there is noch chance to get a stable status with that EF-firmware.

Is there any chance to DOWNGRADE the firmware? Or to upgrade the HACS-integration?

**Comment by Maxctran** [comment]
Well I didn't get round to updating the firmware and it looks like I was lucky to hold off as the last 2 messages seems to contradict the first and it does stop Home Assistant integration from working properly? Anyone else done it and worked out what the issue is and got it connected? @vwt12eh8 @mattwells @Ne0-Hack3r

**Comment by Ne0-Hack3r** [comment]
> Well I didn't get round to updating the firmware and it looks like I was lucky to hold off as the last 2 messages seems to contradict the first and it does stop Home Assistant integration from working properly? Anyone else done it and worked out what the issue is and got it connected? @vwt12eh8 @mattwells @Ne0-Hack3r

I have not updated past .49 but I suspect it is the WiFi update not the system firmware that closed the port again... Very frustrated with EF in general when it comes to any sort of official integration and their incessant moves to make everything totally cloud dependent.

**Comment by imbrianj** [comment]
I've upgraded to v3.0.2.25(Wi-Fi) last night and the port is now closed / integration no longer works.

I've filed a support ticket with Ecoflow to see if they can roll me back to v3.0.2.21(Wi-Fi) which was working wonderfully.

**Comment by Maxctran** [comment]
> I've upgraded to v3.0.2.25(Wi-Fi) last night and the port is now closed / integration no longer works.
> 
> I've filed a support ticket with Ecoflow to see if they can roll me back to v3.0.2.21(Wi-Fi) which was working wonderfully.

Like I said in last comment I haven't risked updating it. I won't now unless it mandatory for it to continue working with Ecoflow app as I still need the automation options on the Smart Home Panel that Home Assistant integration can't control.

**Comment by Ne0-Hack3r** [comment]
> I've upgraded to v3.0.2.25(Wi-Fi) last night and the port is now closed / integration no longer works.
> 
> I've filed a support ticket with Ecoflow to see if they can roll me back to v3.0.2.21(Wi-Fi) which was working wonderfully.

@imbrianj - any word back from EF support? What we really want is an update with the port open again and for them stop closing it with future updates...

**Comment by imbrianj** [comment]
I upgraded on the 15th, immediately saw that v3.0.2.25(Wi-Fi) blocked the API and submitted a ticket to support@ecoflow.com that night.  They responded the next day asking for the serial number and they said they'd get a downgrade sent to my device "in the next few days."  True to their word, I got the downgrade today, 4 days after my initial query.  I'm now back on v3.0.2.21(Wi-Fi) with the working integration.

I did not explicitly ask for the feature to be added to future firmwares but I did make it clear as to why I wanted the downgrade.

**Comment by Ne0-Hack3r** [comment]
> I upgraded on the 15th, immediately saw that v3.0.2.25(Wi-Fi) blocked the API and submitted a ticket to [support@ecoflow.com](mailto:support@ecoflow.com) that night. They responded the next day asking for the serial number and they said they'd get a downgrade sent to my device "in the next few days." True to their word, I got the downgrade today, 4 days after my initial query. I'm now back on v3.0.2.21(Wi-Fi) with the working integration.
> 
> I did not explicitly ask for the feature to be added to future firmwares but I did make it clear as to why I wanted the downgrade.

Thanks for that update!

**Comment by ebeiersdorfer** [comment]
Also confirming that on v3.0.2.25(Wi-Fi) I could not enroll a new DP via this integration. I emailed supported and they queued up a downgrade for me to v3.0.2.21(Wi-Fi) and it instantly added. 

Also for whatever odd reason, my first DP I purchased about a year ago has never really attempted to update the WiFi version, but I won't complain with the lockout.

**Comment by Ne0-Hack3r** [comment]
> Also confirming that on v3.0.2.25(Wi-Fi) I could not enroll a new DP via this integration. I emailed supported and they queued up a downgrade for me to v3.0.2.21(Wi-Fi) and it instantly added.
> 
> Also for whatever odd reason, my first DP I purchased about a year ago has never really attempted to update the WiFi version, but I won't complain with the lockout.

Different batches of DP builds have different WiFi chips. Not all need the 3.0.2.25 update (that closes the port).
