### ISSUE TITLE
Cannot add Delta Pro

### ISSUE THREAD

**Issue by iBobik** [vwt12eh8/hassio-ecoflow#99]
Trying to add my new station with FW 1.0.1.61, but after add it reports error:
```
Logger: homeassistant.config_entries
Source: config_entries.py:399
First occurred: 21:13:12 (1 occurrences)
Last logged: 21:13:12

Error setting up entry DELTA Pro 050002 for ecoflow
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 399, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ecoflow/__init__.py", line 275, in async_setup_entry
    hass.config_entries.async_setup_platforms(entry, _PLATFORMS)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'
```

**Comment by iBobik** [comment]
Duplicate of #76
